@extends('layout.app')
@section('title', 'Zenique Salon & Spa - Your Place to Relax in Tulamben, Bali')
@section('content')

    <section class="relative h-[80vh] bg-cover bg-center" style="background-image: url('{{ asset('images/hero-background.jpg') }}');">
        <div class="absolute inset-0 bg-black/30"></div>
        <div class="relative container mx-auto px-6 h-full flex flex-col justify-center text-white">
            <div class="max-w-xl"><p class="text-xl font-semibold">WELCOME TO ZENIQUE</p><h1 class="text-5xl md:text-7xl font-serif font-bold mt-4 leading-tight">Your Sanctuary of Beauty & Serenity.</h1><p class="mt-6 text-lg">Nikmati sentuhan kemewahan dan relaksasi mendalam dengan perawatan terbaik kami.</p><a href="#services" class="btn-primary mt-8 inline-block px-8 py-4 font-semibold">Lihat Perawatan Kami</a></div>
        </div>
    </section>
    
    <section id="services" class="py-24 relative overflow-hidden">
        <div class="absolute top-0 right-0 transform translate-x-1/4 -translate-y-1/4 -z-10"><svg width="300" height="300" viewBox="0 0 100 100" class="text-green-zen opacity-10"><path d="M50 100C50 100 85 75 95 50C105 25 85 0 85 0C85 0 65 20 50 40C35 20 15 0 15 0C15 0 -5 25 5 50C15 75 50 100 50 100Z" fill="currentColor"/></svg></div>
        <div class="container mx-auto px-6">
            <div class="text-center" data-aos="fade-up"><p class="text-pink-zen font-semibold">OUR TREATMENTS</p><h2 class="text-5xl font-serif mt-2 reveal-text text-green-zen">What We're Offering</h2></div>
            <div class="grid md:grid-cols-3 gap-8 mt-12"><div class="bg-white/50 backdrop-blur-sm rounded-lg shadow-lg p-8 text-center flex flex-col items-center card-hover-effect" data-aos="fade-up" data-aos-delay="0"><div class="w-32 h-32 rounded-full overflow-hidden border-4 border-white"><img src="{{ asset('images/service-beauty.jpg') }}" alt="Beauty Treatments" class="w-full h-full object-cover"></div><h3 class="text-3xl font-serif mt-6 text-green-zen">Beauty Treatments</h3><p class="mt-2 text-gray-600 flex-grow">Tingkatkan kecantikan alami Anda melalui rangkaian perawatan peremajaan kami.</p><a href="{{ route('services') }}" class="mt-6 font-bold text-pink-zen hover:underline">Lihat Detail →</a></div><div class="bg-white/50 backdrop-blur-sm rounded-lg shadow-lg p-8 text-center flex flex-col items-center card-hover-effect" data-aos="fade-up" data-aos-delay="150"><div class="w-32 h-32 rounded-full overflow-hidden border-4 border-white"><img src="{{ asset('images/service-massage.jpg') }}" alt="Massage Treatments" class="w-full h-full object-cover"></div><h3 class="text-3xl font-serif mt-6 text-green-zen">Massage Treatments</h3><p class="mt-2 text-gray-600 flex-grow">Bersantailah dengan pijat ahli kami, meleburkan stres dan mengembalikan ketenangan.</p><a href="{{ route('services') }}" class="mt-6 font-bold text-pink-zen hover:underline">Lihat Detail →</a></div><div class="bg-white/50 backdrop-blur-sm rounded-lg shadow-lg p-8 text-center flex flex-col items-center card-hover-effect" data-aos="fade-up" data-aos-delay="300"><div class="w-32 h-32 rounded-full overflow-hidden border-4 border-white"><img src="{{ asset('images/service-nails.jpg') }}" alt="Body Treatments" class="w-full h-full object-cover"></div><h3 class="text-3xl font-serif mt-6 text-green-zen">Body Treatments</h3><p class="mt-2 text-gray-600 flex-grow">Perawatan untuk mengangkat sel kulit mati dan menutrisi kulit Anda agar halus & bercahaya.</p><a href="{{ route('services') }}" class="mt-6 font-bold text-pink-zen hover:underline">Lihat Detail →</a></div></div>
        </div>
    </section>

    <section class="py-24">
        <div class="container mx-auto px-6">
            <div class="text-center" data-aos="fade-up"><h2 class="text-5xl font-serif mt-2 reveal-text text-green-zen">Zenique dalam Angka</h2></div>
            <div class="grid grid-cols-2 md:grid-cols-4 gap-8 mt-16 text-center">
                <div data-aos="fade-up" data-aos-delay="0"><h3 class="text-6xl font-serif text-pink-zen"><span class="counter" data-count="5">0</span>+</h3><p class="mt-2 text-lg text-gray-600">Tahun Pengalaman</p></div>
                <div data-aos="fade-up" data-aos-delay="100"><h3 class="text-6xl font-serif text-pink-zen"><span class="counter" data-count="100">0</span>+</h3><p class="mt-2 text-lg text-gray-600">Jenis Perawatan</p></div>
                <div data-aos="fade-up" data-aos-delay="200"><h3 class="text-6xl font-serif text-pink-zen"><span class="counter" data-count="100">0</span>%</h3><p class="mt-2 text-lg text-gray-600">Produk Alami</p></div>
                <div data-aos="fade-up" data-aos-delay="300"><h3 class="text-6xl font-serif text-pink-zen"><span class="counter" data-count="100">0</span>+</h3><p class="mt-2 text-lg text-gray-600">Klien Bahagia</p></div>
            </div>
        </div>
    </section>

    <section class="relative bg-cover bg-center py-24" style="background-image: url('{{ asset('images/cta-background.jpg') }}');">
        <div class="absolute inset-0 bg-black/50"></div><div class="relative container mx-auto px-6 grid md:grid-cols-2 gap-12 items-center text-white"><div data-aos="fade-right"><p class="font-semibold">APA LAGI YANG KAMI LAKUKAN</p><h2 class="text-5xl font-serif mt-2">Dapatkan Pengalaman Spa Tak Terlupakan bersama Zenique</h2></div><div data-aos="fade-left"><ul class="space-y-3 text-lg"><li class="flex items-center"><svg class="w-6 h-6 text-pink-zen mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> Massage Treatments</li><li class="flex items-center"><svg class="w-6 h-6 text-pink-zen mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> Hair Treatments</li><li class="flex items-center"><svg class="w-6 h-6 text-pink-zen mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> Nail Treatments</li><li class="flex items-center"><svg class="w-6 h-6 text-pink-zen mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> Beauty Treatments</li><li class="flex items-center"><svg class="w-6 h-6 text-pink-zen mr-3" fill="currentColor" viewBox="0 0 20 20"><path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd"></path></svg> Waxing Treatments</li></ul></div></div>
    </section>

    <section class="py-24 relative overflow-hidden">
        <div class="absolute bottom-0 left-0 transform -translate-x-1/4 translate-y-1/4 -z-10"><svg width="300" height="300" viewBox="0 0 100 100" class="text-pink-zen opacity-10"><path d="M50 100C50 100 85 75 95 50C105 25 85 0 85 0C85 0 65 20 50 40C35 20 15 0 15 0C15 0 -5 25 5 50C15 75 50 100 50 100Z" fill="currentColor"/></svg></div>
        <div class="container mx-auto px-6">
            <div class="text-center" data-aos="fade-up"><p class="text-pink-zen font-semibold">ULASAN PELANGGAN</p><h2 class="text-5xl font-serif mt-2 reveal-text text-green-zen">Apa Kata Mereka</h2></div>
            <div class="grid md:grid-cols-3 gap-8 mt-12"><div class="bg-white/50 backdrop-blur-sm p-8 rounded-lg shadow-lg card-hover-effect" data-aos="fade-up" data-aos-delay="0"><div class="flex items-center mb-4"><div class="text-yellow-400">★★★★★</div></div><p class="text-gray-600 italic">"Pijat Bali terbaik yang pernah saya coba! Tempatnya bersih dan menenangkan. Stafnya sangat ramah dan profesional..."</p><p class="font-bold mt-4">- Sarah J.</p></div><div class="bg-white/50 backdrop-blur-sm p-8 rounded-lg shadow-lg card-hover-effect" data-aos="fade-up" data-aos-delay="150"><div class="flex items-center mb-4"><div class="text-yellow-400">★★★★★</div></div><p class="text-gray-600 italic">"Pengalaman creambath yang luar biasa. Pijatan kepalanya membuat semua stres hilang. Rambut saya jadi sangat lembut..."</p><p class="font-bold mt-4">- Michael B.</p></div><div class="bg-white/50 backdrop-blur-sm p-8 rounded-lg shadow-lg card-hover-effect" data-aos="fade-up" data-aos-delay="300"><div class="flex items-center mb-4"><div class="text-yellow-400">★★★★★</div></div><p class="text-gray-600 italic">"Suasana spanya sangat nyaman dan privat. Saya mencoba paket manikur dan pedikur, hasilnya sangat rapi dan bersih..."</p><p class="font-bold mt-4">- Emily R.</p></div></div>
        </div>
    </section>

    <section class="py-24">
        <div class="container mx-auto px-6 max-w-4xl">
            <div class="text-center" data-aos="fade-up"><p class="text-pink-zen font-semibold">PERTANYAAN UMUM</p><h2 class="text-5xl font-serif mt-2 reveal-text text-green-zen">Yang Sering Ditanyakan</h2></div>
            <div class="space-y-4 mt-12" data-aos="fade-up" data-aos-delay="100">
                <details class="group bg-white/50 backdrop-blur-sm p-6 rounded-lg shadow-lg"><summary class="font-semibold text-lg cursor-pointer flex justify-between items-center text-green-zen">Apakah saya perlu membuat janji temu terlebih dahulu?<span class="text-pink-zen transform group-open:rotate-45 transition-transform text-2xl">+</span></summary><p class="mt-4 text-gray-600">Sangat disarankan untuk membuat janji temu terlebih dahulu untuk memastikan ketersediaan terapis kami, terutama pada akhir pekan. Namun, kami juga menerima pelanggan yang datang langsung jika ada slot yang tersedia.</p></details>
                <details class="group bg-white/50 backdrop-blur-sm p-6 rounded-lg shadow-lg"><summary class="font-semibold text-lg cursor-pointer flex justify-between items-center text-green-zen">Perawatan apa yang paling direkomendasikan untuk relaksasi?<span class="text-pink-zen transform group-open:rotate-45 transition-transform text-2xl">+</span></summary><p class="mt-4 text-gray-600">Untuk relaksasi maksimal, kami sangat merekomendasikan paket "Traditional Balinese Massage" yang dikombinasikan dengan "Aromatherapy". Pijatan tradisional akan melemaskan otot-otot yang tegang, sementara aromaterapi akan menenangkan pikiran Anda.</p></details>
                <details class="group bg-white/50 backdrop-blur-sm p-6 rounded-lg shadow-lg"><summary class="font-semibold text-lg cursor-pointer flex justify-between items-center text-green-zen">Bolehkah saya membuat janji di luar jam operasional?<span class="text-pink-zen transform group-open:rotate-45 transition-transform text-2xl">+</span></summary><p class="mt-4 text-gray-600">Ya, kami fleksibel. Silakan hubungi kami langsung melalui WhatsApp untuk mendiskusikan jadwal khusus di luar jam buka kami (09:00 - 19:00). Kami akan berusaha sebaik mungkin untuk mengakomodasi permintaan Anda.</p></details>
            </div>
        </div>
    </section>
@endsection